version: '3.9'

x-deploy: &deploy
  deploy:
    resources:
      limits:
        memory: 1g

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wordanalyzer
    volumes:
      - pgdata:/var/lib/postgresql/data
    <<: *deploy

  web:
    build: .
    working_dir: /app
    command: python manage.py runserver --noreload 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    <<: *deploy

  redis:
    image: redis:latest
    <<: *deploy

  celery_worker:
    build: .
    working_dir: /app
    command: celery -A wordanalyzer worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    <<: *deploy

volumes:
  pgdata:
